"""AI documentation generation with deterministic templates as fallback."""
from __future__ import annotations

import asyncio
import json
from pathlib import Path
from typing import Sequence

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.logging_config import get_logger
from app.models.analysis import Document
from app.models.repository import Repository
from app.repositories.analysis_repository import DocumentRepository
from app.services.ai.factory import get_ai_provider
from app.services.ai.prompts import DOC_SPECS, DOC_SYSTEM, doc_prompt
from app.services.code_analyzer import code_analyzer

logger = get_logger(__name__)

DEFAULT_DOC_TYPES = list(DOC_SPECS.keys())


def _tree_lines(node: dict, prefix: str = "", depth: int = 0, limit: int = 60) -> list[str]:
    lines: list[str] = []
    if depth > 3 or len(lines) > limit:
        return lines
    for child in (node.get("children") or [])[:20]:
        marker = "/" if child.get("type") == "dir" else ""
        lines.append(f"{prefix}- {child.get('name')}{marker}")
        if child.get("type") == "dir":
            lines.extend(_tree_lines(child, prefix + "  ", depth + 1, limit))
    return lines[:limit]


def fallback_document(doc_type: str, repo: Repository) -> str:
    deps = repo.dependencies or []
    metrics = repo.metrics or {}
    env_vars = metrics.get("env_vars", [])
    tree = "\n".join(_tree_lines(repo.file_tree or {})) or "- (structure unavailable)"
    dep_table = "\n".join(
        f"| `{d.get('name')}` | {d.get('version') or 'unpinned'} | {d.get('ecosystem', '-')} | {d.get('kind', 'runtime')} |"
        for d in deps[:40]
    ) or "| _none detected_ | - | - | - |"
    install_cmd = {
        "npm": "npm install", "yarn": "yarn install", "pnpm": "pnpm install", "pip": "pip install -r requirements.txt",
        "poetry/pip": "poetry install", "Maven": "mvn install", "Gradle": "./gradlew build",
        "Go Modules": "go mod download", "Cargo": "cargo build",
    }.get(repo.package_manager, "# install dependencies with your package manager")

    if doc_type == "readme":
        return f"""# {repo.name}

{repo.description or f'A {repo.primary_language} {repo.project_type.lower()} built with {repo.framework}.'}

## Overview

| Property | Value |
| --- | --- |
| Primary language | {repo.primary_language} |
| Framework | {repo.framework} |
| Architecture | {repo.architecture} |
| Project type | {repo.project_type} |
| Package manager | {repo.package_manager} |
| Build tool | {repo.build_tool} |
| Files | {repo.file_count} |
| Lines of code | {repo.total_lines} |

## Tech stack

{", ".join(f"`{k}`" for k in (repo.languages or {}).keys()) or "n/a"}

## Getting started

```bash
{install_cmd}
```

Entrypoints detected: {", ".join(f"`{e}`" for e in (repo.entrypoints or [])) or "not detected"}

## Project structure

```
{tree}
```

## Dependencies

| Package | Version | Ecosystem | Type |
| --- | --- | --- | --- |
{dep_table}

> Generated by the AI Software Engineering Assistant using static analysis
> (configure `GEMINI_API_KEY` for full AI-authored documentation).
"""
    if doc_type == "structure":
        return f"# Folder Structure Guide\n\n```\n{tree}\n```\n\nEntrypoints: {', '.join(repo.entrypoints or []) or 'n/a'}\n"
    if doc_type == "dependencies":
        return f"# Dependency Documentation\n\n| Package | Version | Ecosystem | Type |\n| --- | --- | --- | --- |\n{dep_table}\n"
    if doc_type == "environment":
        block = "\n".join(f"{name}=" for name in env_vars) or "# no environment variables detected"
        return f"# Environment Variables\n\nDetected {len(env_vars)} referenced variables.\n\n```env\n{block}\n```\n"
    if doc_type == "installation":
        return f"""# Installation Guide

## Prerequisites
- {repo.primary_language} toolchain
- {repo.package_manager} package manager

## Steps
```bash
git clone <repository-url>
cd {repo.name}
{install_cmd}
```

## Verify
Run the detected entrypoint: `{(repo.entrypoints or ['<entrypoint>'])[0]}`
"""
    if doc_type == "deployment":
        return f"""# Deployment Guide

Build tool: **{repo.build_tool}**. Containerisation detected: **{bool(metrics.get('has_dockerfile'))}**.
CI pipeline detected: **{bool(metrics.get('has_ci'))}**.

1. Build the artefact with `{repo.build_tool}`.
2. Provide the environment variables documented in the Environment Variables guide.
3. Run behind a reverse proxy with TLS termination and health checks.
4. Ship logs and metrics to your observability stack, and keep a rollback tag available.
"""
    if doc_type == "architecture":
        return f"""# Architecture Documentation

**Style:** {repo.architecture}

The project is a {repo.project_type.lower()} implemented in {repo.primary_language} on {repo.framework}.
Static analysis found {repo.file_count} files ({repo.total_lines} lines) with
{metrics.get('code_files', 0)} source files and {metrics.get('dependency_count', 0)} dependencies.

## Language distribution
```json
{json.dumps(repo.languages or {}, indent=2)}
```

## Static metrics
```json
{json.dumps({k: v for k, v in metrics.items() if k != 'env_vars'}, indent=2)}
```
"""
    if doc_type == "api":
        return (
            "# API Documentation\n\nNo AI provider configured, so endpoint extraction is limited.\n\n"
            f"Detected entrypoints:\n\n" + ("\n".join(f"- `{e}`" for e in (repo.entrypoints or [])) or "- none")
        )
    return f"# {DOC_SPECS.get(doc_type, {}).get('title', doc_type.title())}\n\nStatic summary for **{repo.name}** ({repo.primary_language} / {repo.framework}).\n"


class DocumentationService:
    def __init__(self, session: AsyncSession) -> None:
        self.session = session
        self.docs = DocumentRepository(session)

    async def generate(
        self, repo: Repository, doc_types: Sequence[str] | None = None, regenerate: bool = True
    ) -> list[Document]:
        types = [t for t in (doc_types or DEFAULT_DOC_TYPES) if t in DOC_SPECS] or DEFAULT_DOC_TYPES
        provider = get_ai_provider()
        root = Path(repo.storage_path)
        bundle = ""
        context = ""
        if root.exists():
            analysis = await asyncio.to_thread(code_analyzer.analyze, root)
            context = analysis.as_context()
            bundle = await asyncio.to_thread(code_analyzer.select_code_bundle, root, analysis, 10)

        results: list[Document] = []
        for doc_type in types:
            existing = await self.docs.get_by_type(repo.id, doc_type)
            if existing and not regenerate:
                results.append(existing)
                continue
            content, ai_powered = "", False
            if provider.available and bundle:
                try:
                    content = await provider.generate_text(
                        doc_prompt(doc_type, context, bundle), system=DOC_SYSTEM, temperature=0.35
                    )
                    ai_powered = bool(content.strip())
                except Exception as exc:  # noqa: BLE001
                    logger.warning("Doc generation failed (%s): %s", doc_type, str(exc)[:200])
            if not content.strip():
                content = fallback_document(doc_type, repo)
            title = DOC_SPECS[doc_type]["title"]
            if existing:
                existing.content = content
                existing.title = title
                existing.ai_powered = ai_powered
                results.append(existing)
            else:
                results.append(
                    await self.docs.create(
                        repository_id=repo.id, doc_type=doc_type, title=title,
                        content=content, ai_powered=ai_powered,
                    )
                )
        await self.session.commit()
        return results
